version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium-tests
    user: root  # Запуск контейнера от имени root
    volumes:
      - ./Nintondo:/usr/workspace/Nintondo
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    working_dir: /usr/workspace/Nintondo/AutoTests/tests
    command: /bin/sh -c "ls -la && pytest -sv /usr/workspace/Nintondo/AutoTests/tests/mane_site_tests/test_connect.py --alluredir=/usr/workspace/allure-results"
    environment:
      - DISPLAY=${DISPLAY}
    ports:
      - "4444:4444"
    networks:
      - selenium_network

  allure:
    image: frankescobar/allure-docker-service:latest
    container_name: allure-report
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    ports:
      - "4040:4040"
    entrypoint: /bin/sh -c "chmod -R 777 /app/allure-results /app/allure-report && allure generate /app/allure-results --clean -o /app/allure-report"

networks:
  selenium_network:
    driver: bridge